# -*- coding: utf-8 -*-
"""panda1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZjvsdGiUTFOl__9pDBPMGcKQRX-JkkKh
"""

import pandas as pd

dd = pd.read_csv('Data.csv')
print(dd)

weather_data = {
    'day': ['1/1/2020', '1/2/2020', '1/3/2020', '1/4/2020', '1/5/2020', '1/6/2020'],
    'temp': [32, 35, 28, 24, 32, 31],
    'windspeed': [6, 7, 2, 7, 4, 2],
    'event': ['Rain', 'Sunny', 'snow', 'snow', 'Rain', 'Sunny']
}

print(weather_data['day'])

df = pd.DataFrame(weather_data)
print(df)

df[['event', 'day']]

df['temp'].max()

df.describe()

df[df.event == 'snow']

#df[['day', 'temp']][df.temp == df['temp'].max()]
#df[['day', 'temp']][df.temp >=30]
df['day'][df.temp == df['temp'].max()]

df.index

print(df)

x = df.iloc[:, :-1]
print(x)

y = df.iloc[:, -1]
print(y)

